added varios fixes to the build system. --with-r2test is now required to compile the r2test tool
git-svn-id: svn://libopenr2.org/openr2/trunk@12 c87312dc-f89b-4d16-81b4-35530099f826

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1464,6 +1464,8 @@ Optional Packages:
   --with-pic              try to use only PIC/non-PIC objects [default=use
                           both]
   --with-tags[=TAGS]      include additional configurations [automatic]
+  --with-r2test           enable the r2test program. You will need spandsp
+                          installed.
 
 Some influential environment variables:
   CC          C compiler command
@@ -3540,8 +3542,6 @@ else
 fi
 
 
-CFLAGS='-ggdb3 -O0 -Wall -D_GNU_SOURCE'
-LD_FLAGS=''
 # Check whether --enable-shared was given.
 if test "${enable_shared+set}" = set; then
   enableval=$enable_shared; p=${PACKAGE-default}
@@ -19764,9 +19764,107 @@ LIBTOOL='$(SHELL) $(top_builddir)/libtool'
 
 
 
+
+cat >>confdefs.h <<\_ACEOF
+#define _GNU_SOURCE
+_ACEOF
+
+
+CFLAGS='-ggdb3 -O0 -Wall'
+LD_FLAGS=''
+
 ac_config_files="$ac_config_files Makefile src/Makefile"
 
-if test "${ac_cv_header_spandsp_h+set}" = set; then
+
+
+# Check whether --with-r2test was given.
+if test "${with_r2test+set}" = set; then
+  withval=$with_r2test;
+else
+  with_r2test=no
+fi
+
+LIBSPANDSP=
+if test "x$with_r2test" != xno; then
+  { echo "$as_me:$LINENO: checking for r2_mf_tx_init in -lspandsp" >&5
+echo $ECHO_N "checking for r2_mf_tx_init in -lspandsp... $ECHO_C" >&6; }
+if test "${ac_cv_lib_spandsp_r2_mf_tx_init+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lspandsp  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char r2_mf_tx_init ();
+int
+main ()
+{
+return r2_mf_tx_init ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_spandsp_r2_mf_tx_init=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_spandsp_r2_mf_tx_init=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_spandsp_r2_mf_tx_init" >&5
+echo "${ECHO_T}$ac_cv_lib_spandsp_r2_mf_tx_init" >&6; }
+if test $ac_cv_lib_spandsp_r2_mf_tx_init = yes; then
+  if test "${ac_cv_header_spandsp_h+set}" = set; then
   { echo "$as_me:$LINENO: checking for spandsp.h" >&5
 echo $ECHO_N "checking for spandsp.h... $ECHO_C" >&6; }
 if test "${ac_cv_header_spandsp_h+set}" = set; then
@@ -19917,6 +20015,23 @@ echo "${ECHO_T}$ac_cv_header_spandsp_h" >&6; }
 fi
 if test $ac_cv_header_spandsp_h = yes; then
   build_r2test=yes
+else
+  { { echo "$as_me:$LINENO: error: --with-r2test was given but spandsp.h was not found.
+See \`config.log' for more details." >&5
+echo "$as_me: error: --with-r2test was given but spandsp.h was not found.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+else
+  { { echo "$as_me:$LINENO: error: --with-r2test was given but libspandsp.so was not found.
+See \`config.log' for more details." >&5
+echo "$as_me: error: --with-r2test was given but libspandsp.so was not found.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 fi
 
 
@@ -19929,6 +20044,7 @@ else
   WANT_R2TEST_TRUE='#'
   WANT_R2TEST_FALSE=
 fi
+
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
